#!/bin/bash

if [ ! -f config.mak ]; then
	echo run ./configure first. See ./configure -h
	exit 2
fi
source config.mak

qemu="${QEMU:-qemu-system-arm}"
testdev=virtio-testdev

if ! $qemu -device '?' 2>&1 | grep $testdev > /dev/null; then
	qpath=$(which $qemu 2>/dev/null)
	if [ "$qpath" ]; then
		echo $qpath doesn\'t support virtio-testdev. Exiting.
	else
		echo $qemu not found.
	fi
	exit 2
fi

command="$qemu -device $testdev -display none -serial stdio "
command+="-M virt -cpu $PROCESSOR "
#command+="-enable-kvm "
command+="-kernel"

echo $command "$@"
$command "$@"
ret=$?
echo Return value from qemu: $ret
exit $ret
